### ISSUE TITLE
It seems the bilinear sampling implementation is buggy.

### ISSUE THREAD

**Issue by nnop** [Ignotus/theano-roi-align#2]
According to your codes:
https://github.com/Ignotus/theano-roi-align/blob/9db8b8b483e368e36432481f735c0ca6d125eb2e/roi_align.cu#L116-L124, in the forward pass, if the feature coordinate lies exactly on an integer position, then `x_left == x_right == w` (same for `y`), the feature value would be accumulated by 4 times.

Maybe It should be:

```c++
 Dtype val = 0; 
 if (is_top_left_in) 
   val += (1 - w + x_left) * (h - y_bottom) * bottom_data[top_left_index]; 
 if (is_top_right_in) 
   val += (w - x_left) * (h - y_bottom) * bottom_data[top_right_index]; 
 if (is_bottom_left_in) 
   val += (1 - w + x_left) * (1 - h + y_bottom) * bottom_data[bottom_left_index]; 
 if (is_bottom_right_in) 
   val += (w - x_left) * (1 - h + y_bottom) * bottom_data[bottom_right_index]; 
```

`x_right` and `y_top` are not necessary.

FYI.

**Comment by Ignotus** [comment]
What you proposed and what in the code is mathematically the same.

(1 - y_top + h) == (h - y_bottom)
(w - x_left) == (1 - x_right + w)

- Minh

**Comment by Ignotus** [comment]
Upd: I think you are right. I will update the source code accordingly. Thank you!

- Minh

Upd: Did you check if it's really an issue on training? Even if it happens (which should be rare since a variable is float) and expectation of your gradient should be correct anyway.
