### ISSUE TITLE
Compile error in roi_align.cu

### ISSUE THREAD

**Issue by Andrea2202** [Ignotus/theano-roi-align#3]
Hi, 
in the last commit of this file (roi_align.cu) in the function ROIAlignForward you removed y_top and x_right variables but these varaibles are still in the code.

int top_left_index =  **y_top** * width + x_left;
        int top_right_index = **y_top** * width + x_right;
        int bottom_left_index = y_bottom * width + x_left;
        int bottom_right_index = y_bottom * width + x_right;

        bool is_top_left_in = x_left >= 0 && x_left <= width - 1
            && y_top >= 0 && y_top <= height - 1;
        bool is_top_right_in = x_right >= 0 && **x_right** <= width - 1
            && y_top >= 0 && y_top <= height - 1;
        bool is_bottom_left_in = x_left >= 0 && x_left <= width - 1
            && y_bottom >= 0 && y_bottom <= height - 1;
        bool is_bottom_right_in = x_right >= 0 && x_right <= width - 1
&& y_bottom >= 0 && y_bottom <= height - 1;

**Comment by Ignotus** [comment]
Hi @Andrea2202,

Thank you for the bug report. I have fixed an issue.

Minh
